#pragma once

enum WORK_STATE
{
	WORK_STATE_00_READY_CHECK,
	WORK_STATE_01_CHECKING,
	WORK_STATE_02_CHECK_FINISH,
	WORK_STATE_03_READY_DOWNLOAD,
	WORK_STATE_04_DOWNLOADING,
	WORK_STATE_05_DOWNLOAD_ERROR,
	WORK_STATE_06_ALL_FINISH,
	WORK_STATE_07_WAIT
};